### ISSUE TITLE
%matplotlib widget not working in jupyter lab

### ISSUE THREAD

**Issue by hasibzunair** [matplotlib/jupyter-matplotlib#148]
Running a cell in jupyter lab with `%matplotlib widget` results in: 

```Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …```
Running the cell more than once results in: 

```KeyError: '97acd0c8fb504a2288834b349003b4ae'```

My environment:
* Python 3.6.8
* Matplotlib 3.0.3

**Comment by martinRenou** [comment]
What instructions did you follow for installing `ipympl`?

**Comment by hasibzunair** [comment]
Just `pip install ipympl`.

It works now after running the following bash commands.
```
conda install -y nodejs
pip install --upgrade jupyterlab
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib
jupyter nbextension enable --py widgetsnbextension
```

**Comment by Nestak2** [comment]
Thanks, "restart" was the critical instruction for me. It wasn't enough the quit and start again jupyterlab in the terminal, only after restarting the computer the plots finally worked

**Comment by martinRenou** [comment]
Usually clearing the browser cache is the important step

**Comment by RGD2** [comment]
FWIW I had same problem, but had to avoid using conda, and was required to use virtual envs with python. 
I was able to fix this by following [nodejs's install instructions using a package manager](https://nodejs.org/en/download/package-manager/). In my case this was ubuntu -- so [using nodejs binary distributions from github](https://github.com/nodesource/distributions/blob/master/README.md).

This ended up being something like (in total):
```
mkvirtualenv -p python3.8 jupenv
pip install jupyter matplotlib pandas ipympl tqdm
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

Because of the venv, you later start jupyter with:

    workon jupenv
    jupyter lab

Hope this helps others.

**Comment by Mariveros** [comment]
Same problem here, restarting kernel not work for me. only when I restart jupyter lab from terminal it works. (%matplotlib widget)

**Comment by Samadarshi-Maity** [comment]
upgrade pip
add 
```
pip install ipympl 
```
in anaconda prompt
and restart jupyter notebook
