### ISSUE TITLE
Cannot import name 'ft2font' from 'matplotlib' on windows10

### ISSUE THREAD

**Issue by kurtispykes** [matplotlib/jupyter-matplotlib#155]
I am using a windows 10 machine and using Anaconda 4.7.12. i attempted to `Import matplotlib.pyplot` and got an error. It has been working fine until yesterday. I uninstalled and reinstalled anaconda, as well as uninstalling and re-installing matplotlib. 

Error code on Jupyter notebooks: 
```
--------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ea90a94a94b6> in <module>
      1 import pandas as pd
      2 import numpy as np
----> 3 import matplotlib.pyplot as plt
      4 get_ipython().run_line_magic('matplotlib', 'inline')

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\__init__.py in <module>
    203 
    204 
--> 205 _check_versions()
    206 
    207 

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\__init__.py in _check_versions()
    188     # Quickfix to ensure Microsoft Visual C++ redistributable
    189     # DLLs are loaded before importing kiwisolver
--> 190     from . import ft2font
    191 
    192     for modname, minver in [

ImportError: cannot import name 'ft2font' from 'matplotlib' (C:\Users\kpy\AppData\Roaming\Python\Python37\site-packages\matplotlib\__init__.py)
```

**Comment by tacaswell** [comment]
You have issues with your installation of Matplotlib.  You mention anaconda, but the traceback looks like you are using python installed from a different source (appstore or from python.org?).  I suspect the issue is that your kernel is using a different python than it was a few days ago.

I suggest moving the discussion about how to resolve the installation issues to https://discourse.matplotlib.org/c/community/install .

**Comment by kurtispykes** [comment]
That was exactly the issue it is now debugged. Many thanks!
