### ISSUE TITLE
widget doesn't show coordinates in jupyter lab

### ISSUE THREAD

**Issue by MerlinPendragon** [matplotlib/jupyter-matplotlib#62]
I started using jupyter lab yesterday. The problem is that I cannot get interactive plot in jupyter lab. If I open jupyter notebook,  everything works fine with zooming and coordinates. But it doesn't work in jupyter lab. No coordinates are shown in the corner and zooming is broken.

![image](https://user-images.githubusercontent.com/11793591/43672983-2cce892a-97ed-11e8-97c3-2ce2d90731c2.png)
![image](https://user-images.githubusercontent.com/11793591/43673007-9d1ce94c-97ed-11e8-9d4a-1e39e51b2fdb.png)

I'm using ipympl from Anaconda, together with other packages
```
ipympl                    0.2.1                    py36_0    conda-forge
ipywidgets                7.3.1                    py36_0
widgetsnbextension        3.3.1                    py36_0
ipython                   6.5.0                    py36_0
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.3                    py36_0  
jupyter_console           5.2.0                    py36_1
jupyter_core              4.4.0                    py36_0
jupyterhub                0.8.1                    py36_0    conda-forge
jupyterlab                0.33.4                   py36_0
jupyterlab_launcher       0.11.2                   py36_0
```

**Comment by jasongrout** [comment]
Did you install the jupyterlab widget manager? `jupyter labextension list` to see the lab extensions installed.

`jupyter labextension install @jupyter-widgets/jupyterlab-manager` to install it.

**Comment by MerlinPendragon** [comment]
Yes, I've installed widget manager. But still cannot get it right.

**Comment by SylvainCorlay** [comment]
@MerlinPendragon, I just realized it is not mentioned in Jason's comment, but jupyter-matplotlib itself must be enabled:

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib
```

If this does not work, could you tell me if you see standard jUPyter widgets

```
from ipywidgets import IntSlider
IntSlider()
```

**Comment by MerlinPendragon** [comment]
No, it still does not work. 

The standard jupyter widgets seem to be right
![default](https://user-images.githubusercontent.com/11793591/43727668-330154fa-99d5-11e8-973a-d3da95d54f38.JPG)

**Comment by MerlinPendragon** [comment]
Weird, I tried to change my browser to Safari from Chrome. It turned out that Safari works fine but still cannot get it work in Chrome.

**Comment by MerlinPendragon** [comment]
Following  @feanor12's steps:

> 
> I fixed it by:
> 
> 1. **delete all output cells**
> 2. save notebook
> 3. reload page
> 4. restart kernel
> 5. run with %matplotlib widget
> 

I have fixed the interactivity problem. Note that the first step is vital.

**Comment by claria** [comment]
In my case this issue arises, as soon as i open a notebook including output cells that were created using the `%matplotlib notebook` magic in jupyter notebook. Following the steps of @MerlinPendragon fixes the problem, but i think a more robust solution would be preferable.

**Comment by flutefreak7** [comment]
Thank you guys for finding this!

I'm really glad I went down the rabbit hole again and found this. I tried `%matplotlib widget` a few weeks back and just assumed it was broken and the lack of recent development had me discouraged thinking that for interactivity in JupyterLab everyone was just migrating to bokeh, bqplot, etc.

I must've been trying to use it in a notebook where I had previously used `%matplotlib notebook` because when I start a new notebook it is working now! Yay!  This should be elevated to a note on the readme or in a troubleshooting section of the docs or something.  I just assumed it was broke and not useful for me on my first pass through trying all the JupyterLab things.  As more people migrate from the Classical Notebook to JupyterLab and discover the things that don't work and push through the hassle of installing plugins, etc, every opportunity to ease the transition is helpful.
